{% set version = "0.18.0" %}

package:
  name: torchtext
  version: {{ version }}

source:
  url: https://github.com/pytorch/text/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fe4eb4b361388ef7840dcad117ae95b32252db5520c4eb2b3bead627468fbdf2
  patches:
    - patches/0001-do-not-build-third_party-libs.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - setuptools
    - pip
    - wheel
    - pytorch 2.3.0
    - double-conversion
    - re2
    - sentencepiece
    - utf8proc
  run:
    - python
    - requests
    - tqdm
    - {{ pin_compatible('pytorch') }}

test:
  imports:
    - torchtext
    - torchtext.datasets
    - torchtext.data
    - torchtext.prototype
  source_files:
    - test
  requires:
    - pytest
  commands:
    - pytest -v test

about:
  home: https://github.com/pytorch/text
  # http://zlib.net/zlib_license.html
  license: BSD
  summary: 'Data loaders and abstractions for text and NLP'
  license_file: LICENSE
